image:
  repository: gogs/gogs
  tag: latest
  pullPolicy: IfNotPresent

postgres:
  enabled: true
  image: postgres:15
  user: gogs
  # Provide EITHER password or existingSecret (recommended: use existingSecret)
  password: "" # leave blank if using existingSecret
  # Uncomment and set after creating the secret:
  existingSecret:
     name: gogs-db-secret
     key: postgres-password
  database: gogs
  storage: 5Gi

gogs:
  replicas: 2
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

service:
  type: ClusterIP
  webPort: 3000
  sshPort: 22

persistence:
  enabled: true
  size: 10Gi
  # Using gp2-csi (EBS CSI driver). Change to gp3 later if you add a gp3 StorageClass.
  storageClassName: gp2-csi

ingress:
  enabled: true
  className: alb
  hostname: "" # set when you have a domain, empty suppresses APP_URL
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
  tls:
    enabled: false
    secretName: gogs-tls

