image:
  repository: gogs/gogs
  tag: latest
  pullPolicy: IfNotPresent

postgresql:
  enabled: true
  auth:
    username: gogs
    database: gogs
    # Provide one of: password or existingSecret (secret must have key: postgres-password)
    password: ""        # leave blank if using existingSecret
    existingSecret: ""  # name of secret with key postgres-password
  primary:
    persistence:
      enabled: true
      size: 5Gi
      storageClass: gp2-csi
  architecture: standalone

externalDatabase:
  enabled: false
  host: ""
  port: 5432
  user: gogs
  database: gogs
  existingSecret: ""   # secret containing key postgres-password

gogs:
  replicas: 2
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

service:
  type: ClusterIP
  webPort: 3000
  sshPort: 22

gogsPersistence:
  enabled: true
  size: 10Gi
  storageClassName: gp2-csi

ingress:
  enabled: true
  className: alb
  hostname: "" # set when you have a domain, empty suppresses APP_URL
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
  tls:
    enabled: false
    secretName: gogs-tls

